# Numpy

**Numpy** es una libreria para la ciencia de los datos en Python. Proporciona un objeto **matriz** multidimensional de alto rendimiento y herramientas para trabajar con estas matrices. 

https://numpy.org/

# Arrays

Un array numpy es:

    * Numpy es un paquete que provee a Python con arreglos multidimensionales de alta eficiencia y diseñados para cálculo científico.
    * Los arreglos de NumPy son de tipo estático y homogéneo.
    * Están indexados por una tupla de enteros no negativos. 
    * El número de dimensiones es el rango de la matriz; la forma de una matriz es una tupla de números enteros que dan el tamaño de la matriz a lo largo de cada dimensión.

Podemos inicializar matrices numpy desde listas de Python anidadas y acceder a elementos usando corchetes:


# Instalar numpy

In [ ]:
! pip install numpy

In [ ]:
! conda install numpy

In [ ]:
from numpy import random as r

In [ ]:
#El método choice() devuelve un elemento seleccionado aleatoriamente de la secuencia especificada.

Arreglo = ['Andres','Juan','Pedro','Mateo']
print(r.choice(Arreglo))

In [ ]:
import numpy as np

# Crear una matriz de rango 1 a partir del constructor "array" de numpy
Lista = [34, 25, 7]

vector = np.array(Lista)
print(vector)

In [ ]:
print(type(vector))            # Prints "<class 'numpy.ndarray'>"

In [ ]:
# se imprime el vector
print(f'Vector {vector}')

# se imprime el cuerpo del vector
print(f'\nCuerpo del vector: {vector.shape}')

In [ ]:
print(f'Vector {vector}')

print(f'Selección {vector[0]} {vector[1]} {vector[2]}')

In [ ]:
print(f'Vector {vector}')

# Cambiar un elemento de indice 0 del vector
vector[0] = 5

print(f'Vector {vector}')

In [ ]:
print(f'Vector {vector}')

vector[0] = 34

print(f'\nCuerpo del vector: {vector.shape}')

In [ ]:
Lista = [
    [1,2,3],
    [4,5,6],
    [7,8,9],
]    # Crear una matriz de rango 2

Matriz = np.array(Lista)

print(f'Matriz \n{Matriz}')

In [ ]:
print(f'\nCuerpo del matriz: {Matriz.shape}')                   # Prints "(3, 3)"

In [ ]:
print(f'Vector \n{Matriz}')

print(f'\nSelección: {Matriz[0, 0]} {Matriz[0, 1]} {Matriz[1, 0]}')

In [ ]:
# creo una matriz a partir de la libreria random y método random
matriz = np.random.random((3,3))

print(f'Matris \n{matriz}')

print(f'\nCuerpo del matriz: {matriz.shape}')  

In [ ]:
matriz =  [[10, 20, 30],
           [40, 50, 60],
           [70, 80 , 90]
           ]

arreglo = np.array(matriz)

print(f'Matriz \n{arreglo}')

print(f'\nCuerpo de la matriz: {arreglo.shape}')

Numpy también proporciona muchas funciones para crear matrices:

In [ ]:
# La función .zero permite rellenar una matriz numpy con valores de "cero"
matriz = np.zeros((3,3))

print(f'Matris \n{matriz}')

print(f'\nCuerpo de la matriz: {matriz.shape}')

In [ ]:
# # La función .ones permite rellenar una matriz numpy con valores de "unos"
b = np.ones((5,5))

print(f'Matris \n{b}')

print(f'\nCuerpo de la matriz: {b.shape}')

In [ ]:
# La función .full, devuelve una nueva matriz de forma y tipo dados, es decir, rellena con un valor de relleno
c = np.full((4,8), 2022)

print(f'Matris \n{c}')

print(f'\nCuerpo de la matriz: {c.shape}')

In [ ]:
Lista = [1, 2, 78]

d = np.full((2, 3), Lista)

print(f'Matris \n{d}')

print(f'\nCuerpo del arreglo: {d.shape}')

In [ ]:
# La función eye devuelve una matriz de identidad nxn, es decir, una matriz donde todos sus elementos son cero excepto la diagonal principal

d = np.eye(3)
print(f'Matris \n{d}')

In [ ]:
# Crear una matriz llena de valores aleatorios
MatrizNumerosAleatorios = np.random.random((2,2))

print(f'Matris \n{MatrizNumerosAleatorios}')

print(f'\nCuerpo de la matriz: {MatrizNumerosAleatorios.shape}')

Puede leer sobre otros métodos de creación de matrices en la documentación de Numpy

https://numpy.org/doc/stable/user/basics.creation.html#arrays-creation

In [ ]:
import numpy as np

Arreglo = (
    [1,3,5,7],
    [3,6,1,8],
    [6,8,0,3],
    [2,43,2,8]
    )
     
ArregloNumpy = np.array(Arreglo)

print(f'Matris \n{ArregloNumpy}')

print(f'\nCuerpo de la matriz: {ArregloNumpy.shape}\n')


# Indexación de matrices

Numpy ofrece varias formas de indexar en matrices.

# Rebanar

Similar a las listas de Python, las matrices numpy se pueden cortar. Dado que las matrices pueden ser multidimensionales, debe especificar un segmento para cada dimensión de la matriz:

In [ ]:
import numpy as np

Arreglo = [
    [1,2,3],
    [5,6,7],
    [9,10,11]
    ]

matriz = np.array(Arreglo)

print(f'Matris \n{matriz}')

print(f'\nCuerpo de la matriz: {matriz.shape}')

# [fila:fila, columna,columna]
matrizRebanada = matriz[:2, 1:] #[Desde la fila 0 hasta la fila 1], [Desde los valores 1 hasta el final de la fila]
print('\nMatriz rebanada \n', matrizRebanada)

ElementoDeMatriz = matriz[0, 1]
print(f'\nElemento de la matriz : {ElementoDeMatriz}')

In [ ]:
# La función fliplr invierte el orden de los elementos a lo largo del eje 1(fila - de izquierda a derecha).
print(f'Matriz \n{matriz}\n')

print(f'Matriz invertida: \n {np.fliplr(matriz)}')

In [ ]:
# Cambiar valores en el arreglo
print(f'Matris \n{matriz}')

matriz[0, 0] = 77 

print(f'Matris \n{matriz}')

También puede mezclar la indexación de enteros con la indexación de sectores. Sin embargo, al hacerlo, se obtendrá una matriz de rango más bajo que la matriz original.

In [ ]:
# Indexación de enteros con la indexación de sectores en filas

import numpy as np

Arreglo = [
    [1,2,3,4], 
    [5,6,7,8], 
    [9,10,11,12]
    ]

a = np.array(Arreglo)

print(f'Matris \n{a}')
print(f'\nCuerpo de la matriz {a.shape}')

# Mezclando la indexación de enteros con rebanadas se obtiene una matriz de rango inferior
row_r1 = a[1 , :]    # Vista de rango 1 de la segunda fila
print(f'\nVector resultado : {row_r1} de cuerpo {row_r1.shape}\n')  # Prints "[5 6 7 8] (4,)"

# Usando sólo rebanadas se obtiene un conjunto del mismo rango que en la matriz original:
row_r2 = a[1:2 , :]  # Vista de rango 2 de la segunda fila
print(f'Matriz resultado : {row_r2} de cuerpo {row_r2.shape}')  # Prints [[5 6 7 8]] (1, 4)

In [ ]:
# Indexación de enteros con la indexación de sectores en columnas
matriz = np.array(
    [[1,2,3,4], 
     [5,6,7,8], 
     [9,10,11,12]
])

print(f'Matris \n{matriz}')
print(f'\nCuerpo de la matriz {matriz.shape}')

col_r1 = a[:,1]
print(f'\nCrea un arreglo con el valor [1] de todas las filas: \n{col_r1}')
print(f'\nCuerpo del arreglo resultante {col_r1.shape}')

col_r2 = a[:, 1:2] #Imprimir solo valores de la columna 1
print(f'\nCrea un arreglo de tres filas y una columna (con el valor de la posición [1] de la matriz): \n{col_r2}')
print(f'\nCuerpo de la matriz { col_r2.shape}')

# Indexación de matrices de enteros: 

Cuando indexa matrices de números utilizando la división, la vista de matriz resultante siempre será una submatriz de la matriz original. Por el contrario, la indexación de matrices de enteros le permite construir matrices arbitrarias utilizando los datos de otra matriz. Aquí hay un ejemplo:

In [ ]:
import numpy as np

matriz = np.array(
    [[1, 2], 
     [3, 4], 
     [5, 6]
])

print(f'Matris \n{matriz}')
print(f'\nCuerpo de la matriz {matriz.shape}')

In [ ]:
# Indexación de arreglos enteros. La matriz devuelta tendrá forma (3,2) 
print(f'Matris \n{matriz}')
print(f'Vector resultado \n{matriz[[0, 1, 2], [0, 1, 0]]}') # F  F  F, C  C  C

# Lo anterior es un equivalente a esto:
mismoEjemploOtraForma = np.array([matriz[0, 0], matriz[1, 1], matriz[2, 0]])
print(f'\nMismo vector otra forma: \n{mismoEjemploOtraForma}')

In [ ]:
# Cuando se usa la indexación de arreglos enteros, se puede reutilizar el mismo elemento de la matriz de la fuente:
print(f'Matris \n{matriz}')

print(f'\nVector resultado \n{matriz[[0, 0], [1, 1]]}') # F F C C

# Equivalente al ejemplo anterior de indexación de arreglos enteros

otroVectorResultado = np.array([a[0, 1], a[0, 1]])
print(f'\nVector resultado \n{otroVectorResultado}') # F C , F C

# Indexación de matriz booleana: 

La indexación de matriz booleana le permite seleccionar elementos arbitrarios de una matriz. Con frecuencia, este tipo de indexación se utiliza para seleccionar los elementos de una matriz que satisfacen alguna condición. Aquí hay un ejemplo:

In [ ]:
import numpy as np

matriz = np.array(
    [[1, 2], 
     [3, 4], 
     [5, 6],
     [1, 1]
])

print(f'Matris \n{matriz}')
print(f'\nCuerpo de la matriz {matriz.shape}')

# marca como verdaderos aquellos valores mayores a la codición de verdad
bool_idx = (matriz > 2)
print(f'\nMatriz de verdad \n{bool_idx}')

# Imprime la matriz resultante
print(f'\nMatriz resultado \n {matriz[bool_idx]}')

# Tambien podemos hacer todo lo anterior en una sola declaración:
MayoresADos = matriz[matriz > 2]
print(f'\nMatriz resultado \n {MayoresADos}')

Por brevedad, hemos omitido muchos detalles sobre la indexación de matrices numpy; si quieres saber más debes leer la documentación .  

https://numpy.org/doc/stable/reference/arrays.indexing.html

# Tipos de datos

Cada matriz numpy es una cuadrícula de elementos del mismo tipo. Numpy proporciona un gran conjunto de tipos de datos numéricos que puede utilizar para construir matrices. Numpy intenta adivinar un tipo de datos cuando crea una matriz, pero las funciones que construyen matrices generalmente también incluyen un argumento opcional para especificar explícitamente el tipo de datos. Aquí hay un ejemplo:

In [ ]:
matriz = np.array(
    [[1, 2], 
     [3, 4], 
     [5, 6],
     [1, 1]
])
x = np.array(matriz)
print(f'Matris \n{matriz}')

print(f'\nTipo de datos de la matriz: {matriz.dtype}')
print(type(matriz))

In [ ]:
x = np.array([1., 2.])
   
print(f'Matris \n{x}')

print(f'\nTipo de datos de la matriz: {x.dtype}')

In [ ]:
# Fuerza un tipo de datos en particular

x = np.array([1, 2], dtype = np.int64)
   
print(f'Matris \n{x}')

print(f'\nTipo de datos de la matriz: {x.dtype}')

Puede leer todo sobre numerosos tipos de datos en la documentación .

https://numpy.org/doc/stable/reference/arrays.dtypes.html

# Matemáticas de matriz

Las funciones matemáticas básicas operan por elementos en matrices y están disponibles como sobrecargas de operador y como funciones en el módulo numpy:

In [ ]:
import numpy as np

matrizA = [
    [1,2],
    [3,4]
    ]

x = np.array(matrizA, dtype=np.int32)
print(f'Matris X\n{x}')

matrizB = [
    [5,6],
    [7,8]
    ]

y = np.array(matrizB, dtype=np.float64)
print(f'\nMatris Y\n{y}')

In [ ]:
# Suma de elementos; ambos producen la matriz
print(f'Matris X\n{x}')
print(f'\nMatris Y\n{y}')

print(f'Matriz resultado \n {x + y}')
# La función add permite sumar dos matrices
print(f'\nMatriz resultado \n {np.add(x, y)}')

In [ ]:
# Diferencia de elementos (resta); ambos producen la matriz
print(f'Matris X\n{x}')
print(f'\nMatris Y\n{y}')

print(f'Matriz resultado \n {x - y}')
print(f'\nMatriz resultado \n {np.subtract(x, y)}')

In [ ]:
# Producto de elementos; ambos producen la matriz
print(f'Matris X\n{x}')
print(f'\nMatris Y\n{y}')

print(f'Matriz resultado \n {x * y}')
multiplicar = np.multiply(x, y)
print(f'\nMatriz resultado \n {multiplicar}')

In [ ]:
# División de elemetos; ambos producen la matriz
print(f'Matris X\n{x}')
print(f'\nMatris Y\n{y}')

print(f'Matriz resultado \n {x / y}')

otraMatriz = np.divide(x, y)
print(f'\nMatriz resultado \n {otraMatriz}')

In [12]:
# Raíz cuadrada de elementos; produce la matriz
print(f'Matris X\n{x}')

print(f'\nMatriz resultado \n {np.sqrt(x)}')

Matris X
[[1 2]
 [3 4]]

Matriz resultado 
 [[1.         1.41421356]
 [1.73205081 2.        ]]


Tenga en cuenta que **es una multiplicación por elementos, no una multiplicación de matrices**. En cambio, usamos la función dot para calcular productos internos de vectores, para multiplicar un vector por una matriz y para multiplicar matrices. dot está disponible como función en el módulo numpy y como método de instancia de objetos de matriz:

In [13]:
# suma de productos internos de vectores
import numpy as np

v = np.array([9,10])
w = np.array([11, 12])

sumaProductos1 = v.dot(w)
print(f'\nLa suma de los productos internos es : {sumaProductos1}') #9*11+10*12 = 219

# De otra forma
sumaProductos2 = np.dot(v, w)
print(f'\nLa suma de los productos internos es : {sumaProductos2}') #9*11+10*12 = 219


La suma de los productos internos es : 219

La suma de los productos internos es : 219


In [14]:
# En arreglo de 2x2
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

sumaProductos1 = x.dot(y)
print(f'\nLa suma de los productos internos es : \n{sumaProductos1}') # [1*5+2*7 = 19  1*6+2*8 = 22]  [3*5+4*7 = 43  3*6+4*8 = 50]

# De otra forma
sumaProductos2 = np.dot(x, y)
print(f'\nLa suma de los productos internos es : \n{sumaProductos2}') # [1*5+2*7 = 19  1*6+2*8 = 22]  [3*5+4*7 = 43  3*6+4*8 = 50]


La suma de los productos internos es : 
[[19 22]
 [43 50]]

La suma de los productos internos es : 
[[19 22]
 [43 50]]


Numpy proporciona muchas funciones útiles para realizar cálculos en matrices; uno de los más útiles es sum:

In [15]:
import numpy as np

arreglo = [[1,2],
           [3,4]]

x = np.array(arreglo)

# Calcular la suma de todos los elementos
SumaElementos = np.sum(x)
print(f'Suma de elementos de la matris X\n{SumaElementos}') # 1+3 + 2+4 = 10

# Calcula la suma de cada columna
SumaColumnas = np.sum(x, axis = 0)
print(f'\nSuma de cada columna \n{SumaColumnas}') # 1+3 2+4 Vertical imprime [4 6]

# Calcula la suma de cada fila
SumaFilas = np.sum(x, axis = 1)
print(f'\nSuma de cada fila \n{SumaFilas}') # 1+2 3+4 Horizontal imprime [3 7]

Suma de elementos de la matris X
10

Suma de cada columna 
[4 6]

Suma de cada fila 
[3 7]


Puede encontrar la lista completa de funciones matemáticas proporcionadas por numpy en la documentación.

https://numpy.org/doc/stable/reference/routines.math.html

Además de calcular funciones matemáticas utilizando matrices, con frecuencia necesitamos remodelar o manipular datos en matrices. El ejemplo más simple de este tipo de operación es la transposición de una matriz; para transponer una matriz, simplemente use el **T** atributo de un objeto de matriz:

In [16]:
import numpy as np

Arreglo = [
    [1,2], 
    [3,4]
]

x = np.array(Arreglo)

print(f'Matriz original \n{x}')

# Matriz Transpuesta => Atributo T
print(f'\nMatriz Transpuesta \n{x.T}')

Matriz original 
[[1 2]
 [3 4]]

Matriz Transpuesta 
[[1 3]
 [2 4]]


In [17]:
# Note que tomar la transposición de una matriz de rango 1 no hace nada:

arreglo = [1,2,3]
v = np.array(arreglo)

print(f'Matriz original \n{v}')

# Matriz Transpuesta => Atributo T
print(f'\nMatriz Transpuesta \n{v.T}')

Matriz original 
[1 2 3]

Matriz Transpuesta 
[1 2 3]


Numpy proporciona muchas más funciones para manipular matrices; puedes ver la lista completa en la documentación.
https://numpy.org/doc/stable/reference/routines.array-manipulation.html

# Broadcasting

El Broadcasting es un mecanismo poderoso que permite a numpy trabajar con matrices de diferentes formas al realizar operaciones aritméticas. Con frecuencia tenemos una matriz más pequeña y una matriz más grande, y queremos usar la matriz más pequeña varias veces para realizar alguna operación en la matriz más grande.

Por ejemplo, suponga que queremos agregar un vector constante a cada fila de una matriz. Podríamos hacerlo así:

In [18]:
import numpy as np

# Añadiremos el vector "v" a cada fila de la matriz "x", almacenando el resultado en la matriz "y"
arreglo = [
    [1,2,3], 
    [4,5,6], 
    [7,8,9], 
    [10,11,12]
    ]

x = np.array(arreglo) #4x3

print(f'Matriz original \n{x}')
print(f'\nCuerpo de la matriz {x.shape}\n')

v = np.array([1, 0, 1])

print(f'Vector original \n{v}')
print(f'\nCuerpo de la matriz {v.shape}')

# Crear una matriz vacía con la misma forma que x con la función empty_like
y = np.empty_like(x)

# Agrega el vector "v" a cada fila de la matriz "x" con un bucle explícito.
for i in range(4):
    y[i, :] = x[i, :] + v
print(f'\nMatriz resultado \n{y}')
print(f'\nCuerpo de la matriz {y.shape}\n')

Matriz original 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Cuerpo de la matriz (4, 3)

Vector original 
[1 0 1]

Cuerpo de la matriz (3,)

Matriz resultado 
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]

Cuerpo de la matriz (4, 3)



Esto funciona; sin embargo, cuando la matriz x es muy grande, calcular un bucle explícito en Python podría ser lento. Tenga en cuenta que agregar el vector a cada fila de la matriz x es equivalente a formar una matriz vv apilando múltiples copias de v verticalmente, luego realizando la suma de elementos de x y vv. Podríamos implementar este enfoque de esta manera:

In [ ]:
import numpy as np

# Añadiremos el vector "v" a cada fila de la matriz "x", almacenando el resultado en la matriz "y"

x = np.array(
    [[1,2,3], 
     [4,5,6], 
     [7,8,9], 
     [10,11,12]
]) #4x3

print(f'Matriz original \n{x}')
print(f'Cuerpo de la matriz {x.shape}\n')

v = np.array([1, 0, 1])

print(f'Vector original \n{v}')
print(f'Cuerpo de la matriz {v.shape}\n')

# Amontonar 4 copias de V una encima de la otra con la función tile
vv = np.tile(v, (4, 1))
print(f'Matriz original \n{vv}')

# sumar las 2 matrices desde el método .add de np
print(f'\nMatriz resultado \n{np.add(x,vv)}')
print(f'Cuerpo de la matriz {y.shape}\n')

# El Broadcasting de dos matrices juntas sigue estas reglas:

1. Si las matrices no tienen el mismo rango, anteponga 1 a la forma de la matriz de rango inferior hasta que ambas formas tengan la misma longitud.

2. Se dice que las dos matrices son compatibles en una dimensión si tienen el mismo tamaño en la dimensión, o si una de las matrices tiene el tamaño 1 en esa dimensión.

3. Los arreglos se pueden transmitir juntos si son compatibles en todas las dimensiones.

3. Después de la transmisión, cada matriz se comporta como si tuviese una forma igual al máximo de formas de las dos matrices de entrada.

5. En cualquier dimensión donde una matriz tiene un tamaño 1 y la otra matriz tiene un tamaño mayor que 1, la primera matriz se comporta como si se hubiera copiado a lo largo de esa dimensión.

Ver

https://numpy.org/doc/stable/user/basics.broadcasting.html

http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc

Las funciones que apoyan el Broadcasting se conocen como funciones universales. Puede encontrar la lista de todas las funciones universales en la documentación.

https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs


Asimismo, el Broadcasting suele hacer que su código sea más conciso y rápido, por lo que debe esforzarse por utilizarlo siempre que sea posible.

Documentación Numpy
Esta breve descripción general ha abordado muchas de las cosas importantes que necesita saber sobre numpy, pero está lejos de ser completa. Consulte la referencia de numpy para obtener más información sobre numpy.

https://numpy.org/doc/stable/reference/